### ISSUE TITLE
Anchor top of calendar at one point

### ISSUE THREAD

**Issue by siddharthkp** [rubencodes/recal#1]
Because the size of the calendar depends on the month, the controls jump around making it slightly annoying.

![jumpy](https://user-images.githubusercontent.com/1863771/38765260-f5ae335a-3fdb-11e8-8fea-36be9786c9cf.gif)

I think this can be solved by keeping the top of the calendar fixed at one point and only changing the bottom parts. I have also seen calendars that reserve extra space under them by default to handle such cases.

**Comment by rubencodes** [comment]
Ah yes, this happens in the Live Demo code because it's using Flexbox to vertically center it (and as you pointed out, the "center" changes from month to month). I'll look into adjusting this! Thanks!

**Comment by rubencodes** [comment]
Resolved by eliminating vertical centering in  https://github.com/rubencodes/recal/commit/030794a80775d3bff1c709f38fe3a2a80c6899bb!
